export enum FormGroupType {
  APPLICANT_ADDRESS = "APPLICANT_ADDRESS",
  APPLICANT_AVAILABILITY = "APPLICANT_AVAILABILITY",
  APPLICANT_CONTACT = "APPLICANT_CONTACT",
  APPLICANT_CRIME = "APPLICANT_CRIME",
  APPLICANT_MEDICAL = "APPLICANT_MEDICAL",
  APPLICANT_NAME = "APPLICANT_NAME",
  APPLICANT_RESIDENCY = "APPLICANT_RESIDENCY",
  APPLICANT_TRANSPORTATION = "APPLICANT_TRANSPORTATION",
  APPLICANT_EDUCATION = "APPLICANT_EDUCATION",
  APPLICANT_CERTIFICATIONS = "APPLICANT_CERTIFICATIONS",
  APPLICANT_PRIOR_EMPLOYMENT = "APPLICANT_PRIOR_EMPLOYMENT"
}
