export enum FormGroupType {
  APPLICANT_ADDRESS = "APPLICANT_ADDRESS",
  APPLICANT_AVAILABILITY = "APPLICANT_AVAILABILITY",
  APPLICANT_CONTACT = "APPLICANT_CONTACT",
  APPLICANT_CRIME = "APPLICANT_CRIME",
  APPLICANT_MEDICAL = "APPLICANT_MEDICAL",
  APPLICANT_NAME = "APPLICANT_NAME",
  APPLICANT_RESIDENCY = "APPLICANT_RESIDENCY",
  APPLICANT_TRANSPORTAION = "APPLICANT_TRANSPORTAION"
}
