export enum InputFieldName {
  EMAIL = "email",
  NAME__FIRST = "name,first",
  NAME__LAST = "name,last",
  ADDRESS_CITY = "address,city",
  ADDRESS_POSTAL_CODE = "address,postalcode",
  ADDRESS_STATE = "address,state",
  ADDRESS_STREET = "address,street",
  CONTACT_EMAIL = "contact,email",
  CONTACT_PHONE_CELL = "contact,phone,cell",
  CONTACT_PHONE_HOME = "contact,phone,home",
  CONTACT_EMERGENCY_NAME = "contact,emergency,name",
  CONTACT_EMERGENCY_PHONE = "contact,emergency,phone",
  MEDICAL_CONDITIONS = "medical,conditions",
  MEDICAL_MEDICATIONS = "medical,medications",
  MEDICAL_SMOKE = "medical,smoke",
  MEDICAL_ALCOHOL = "medical,alcohol",
  RESIDENCY_NC_RESIDENT = "residency,nc,resident",
  RESIDENCY_NC_OUTSIDE = "residency,nc,outside",
  RESIDENCY_NC_OUTSIDE_YES = "residency,nc,outside,yes",
  CRIME_CONVICTED = "crime,convicted",
  CRIME_CONVICTED_YES = "crime,convicted,yes"
}
